### ISSUE TITLE
Not all tracks of an album are displayed (Deezer)

### ISSUE THREAD

**Issue by WolfgangDpunkt** [justin025/onthespot#90]
I use Onthespot for audio books.
I notice that the app can't seem to download more than 25 tracks from an album with Deezer.

This “album” has 130 tracks:
https://www.deezer.com/en/album/435313947

But Onthespot only shows the first 23 tracks:
<img width="246" alt="grafik" src="https://github.com/user-attachments/assets/e7d82d0a-327d-4881-9065-49cad082d5f5" />

I observe the same thing in numerous other examples.

**Comment by justin025** [comment]
I can't tell you how grateful I am for you finding this, it has been quite difficult to find albums with >100 songs to test the app properly. Do you happen to have any playlists with more than 100 songs on deezer aswell so I can fix this and verify everything is working properly?

**Comment by WolfgangDpunkt** [comment]
Very gladly, here is an extreme example. An album/book with 680 tracks :-)

https://www.deezer.com/en/album/538311232

**Comment by justin025** [comment]
This build should fix the issue you were facing, dmg is available at the bottom of the page:
https://github.com/justin025/onthespot/actions/runs/12519083560

Did you happen to fix your config error on macos?

**Comment by WolfgangDpunkt** [comment]
Thank you for the improvement!
If I try it with the Robinson book, it will definitely work better.
He finds 75 tracks and at the next try 93.
But he does not find the whole 130.
https://www.deezer.com/en/album/435313947

**Comment by justin025** [comment]
I was able to queue all 130 first try, can you send your logs.
![2024-12-27_14-20](https://github.com/user-attachments/assets/d303fab6-23fc-4400-9ae5-78eb5746fc97)
![2024-12-27_14-22](https://github.com/user-attachments/assets/c5ac3d1e-092f-4018-8602-cad892fa621a)

**Comment by WolfgangDpunkt** [comment]
Thank you for your efforts!
Here comes my logfile:
[onthespot.log](https://github.com/user-attachments/files/18263046/onthespot.log)

Still getting not all tracks: 
<img width="1216" alt="grafik" src="https://github.com/user-attachments/assets/23b5cc6a-efda-4eeb-a5e5-182fc99e3339" />

It may be a solution to download big album in several parts? So only the first 50 tracks, then restart the process and it loads another 50 tracks...

**Comment by justin025** [comment]
According to the logs it seems the tracks are found just fine, it seems to be a key error and the latest build here may fix it:
https://github.com/justin025/onthespot/actions

It might also be related to the region of your deezer account but its difficult to tell considering I don't have your returned log. Please let me know if this fixes it, if not I will add an error catcher

**Comment by WolfgangDpunkt** [comment]
The last version seems to have a new bug, no download is possible, adding to the download queue is confirmed, but then nothing happens.
[onthespot.log](https://github.com/user-attachments/files/18263570/onthespot.log)

**Comment by justin025** [comment]
I'm sorry about this it was a mistake on my part, I pushed a fix. If you would like perhaps it would be easier to debug over something like discord.

**Comment by WolfgangDpunkt** [comment]
Good news!
I tried the [latest version](https://github.com/justin025/onthespot/actions/runs/12524588316) and it worked!
All 130 tracks of the Robinso audio book are found. 
And even the enormous big album/book with 680 tracks works!
Thank you so much for the great solution!
You are doing really very good and meaningful work here, thank you!
